### ISSUE TITLE
Stretched launch screen on Android

### ISSUE THREAD

**Issue by malua** [aparajita/capacitor-splash-screen#4]
Hey aparajita,

I came here because of this thread:
https://github.com/ionic-team/capacitor/issues/1627

And I actually updated your plugin to capacitor 3 because I thought it would fix the issue with stretched android launchscreens. but I think it does not fix that, right?
Your config from the demo repo only shows the splash from the plugin not from native android. so there is this short amount of time, after clicking the app icon, where nothing happens or at least it looks like that to a user.

So my question is can I show a native image splash screen (which is not stretched) before the splash screen of the plugin?
thanks for you answer!

I will push my capacitor 3 code changes to my fork. It works as it is on ios and android. but i am not sure about some of the code changes and have not tested everything. maybe somebody will test and finish it. ( or i would if the plugin can address my issue)

all the best,
lukas

**Comment by aparajita** [comment]
The issue describe in https://github.com/ionic-team/capacitor/issues/1627 happens because the native splash image is full screen (no status bar) and the capacitor image does have a status bar. So of course they are going to scale differently.

I was never able to reliably avoid that (working with Android is a nightmare), so I just show an empty native splash screen and wait for the capacitor splash screen to appear.

**Comment by malua** [comment]
ok thanks fro the clarification. thats how i will do it as well. and i think cordova did that also.
