### ISSUE TITLE
I try to enable the splash screen and after some seconds disable it 

### ISSUE THREAD

**Issue by danielehrhardt** [aparajita/capacitor-splash-screen#9]
![image](https://user-images.githubusercontent.com/19570043/204005192-298e0335-984f-42a5-82ab-695b61317143.png)

**Comment by ZaLiTHkA** [comment]
I noticed the same message this morning. confused me a little since it comes up from calling `.hide()`, but anyways.. just for clarification, this is being thrown from [`SplashScreen.java` line 120](https://github.com/aparajita/capacitor-splash-screen/blob/947d1eed6b6df18f973fa32aa7c0109fb0262be6/android/src/main/java/com/aparajita/capacitor/splashscreen/SplashScreen.java#L120).

this only comes up for me if the app launches without showing any splash screen, which means there is nothing _to hide_, and it doesn't break anything else in my app startup. 🤔 @aparajita is this "expected behaviour", despite the incorrect error message string?

**Comment by danielehrhardt** [comment]
For me even when the SplashScreen is showing it does not work when i try to call hide and show in the app

**Comment by aparajita** [comment]
@danielehrhardt @ZaLiTHkA I can't help anyone without seeing the plugin configuration and your code.
